### ISSUE TITLE
M6 ─ CI/CD & プレビュー

### ISSUE THREAD

**Issue by big-mon** [big-mon/estrivault-blog-app#7]
以下をGitHub Actionsで構築し、Preview URLを発行可能にする:

```yaml
name: Build and Preview
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: '8'
      - name: Install dependencies
        run: pnpm i
      - name: Build Astro blog
        run: pnpm --prefix apps/astro-blog run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/astro-blog/dist
```
